################ string constants #########################

DEN_PUESTO_TRABAJO_OPEN =  "PUESTO TRABAJO OPENPLAN"

DEN_SALA_REUNION_PEQUENA = "SALA REUNION PEQUEÑA"
DEN_SALA_REUNION_GRANDE = "SALA REUNION GRANDE"
DEN_SALA_REUNION_MEDIANA = "SALA REUNION MEDIANA"

DEN_OFICINA_PRIVADA = "OFICINA PRIVADA"

DEN_PHONEBOOTH = "PHONEBOOTH"

DEN_COLABORATIVO_FORMAL = "COLABORATIVO FORMAL"
DEN_COLABORATIVO_INFORMAL = "COLABORATIVO INFORMAL"

DEN_CIRCULACIONES = "CIRCULACIONES"
DEN_SOPORTE = "SOPORTE"


FACTOR_OPEN_PLAN = "FACTOR OPEN PLAN"
FACTOR_CIRCULACION = "FACTOR CIRCULACION"
FACTOR_SOPORTE = "FACTOR SOPORTE"

############### by default values ##########################

GLOBAL_CONFIG_VARS = {
    DEN_PUESTO_TRABAJO_OPEN: 3.26,
    DEN_SALA_REUNION_PEQUENA: 1.73,
    DEN_SALA_REUNION_MEDIANA: 2.16,
    DEN_SALA_REUNION_GRANDE: 27.30,
    DEN_OFICINA_PRIVADA: 9.1,
    DEN_PHONEBOOTH: 3.04,
    DEN_COLABORATIVO_FORMAL: 2.08,
    DEN_COLABORATIVO_INFORMAL: 1.51,
    DEN_CIRCULACIONES: 35.0,
    DEN_SOPORTE: 15.0,
    FACTOR_OPEN_PLAN: 0.9,
    FACTOR_SOPORTE: 15.0,
    FACTOR_CIRCULACION: 35.0
}
